name: test-always

on:
  workflow_dispatch:
    inputs:
      run_job:
        type: boolean
        default: true

jobs:
  test:
    runs-on: ubuntu-latest
    # This makes the job run only if "run_job" input is true
    if: ${{ github.event.inputs.run_job == 'true' }}

    steps:
      - name: Step A — forced skip
        if: false
        run: echo "You should NOT see this."

      - name: Step B — success() || failure()
        if: ${{ success() || failure() }}
        run: echo "B RAN because job is running."

      - name: Status check
        run: echo "Job status ${{ job.status }}"
